"""Generate the authoritative S2_final_included_studies.csv from the
52 PDF files preserved in `data/final_included_papers/`.

This is the table of studies actually included in the synthesis. It is
reconstructed from the surviving PDF corpus because the original
`final_s3_included_20260122_225842.csv` and the per-study extraction
table `s3_extracted_data_full_20260122_233013.csv` were not preserved
in the repository (large CSV/JSON outputs are generated by the scripts
in `operations/src/_archive/scripts/` and not committed).

Each row contains only what can be derived from the filename without
fabrication: a sequential study_id, the DOI (filename with the first
'_' replaced by '/'), and the PDF basename.
"""
from __future__ import annotations
import csv
from pathlib import Path

REPO = Path(__file__).resolve().parents[4]
PDF_DIR = REPO / "data/final_included_papers"
OUT = REPO / "artifacts/data/evidence/supplementary/S2_final_included_studies.csv"


def doi_from_pdf_name(stem: str) -> str:
    return stem.replace("_", "/", 1)


def main() -> None:
    pdfs = sorted(PDF_DIR.glob("*.pdf"))
    if len(pdfs) != 52:
        raise SystemExit(f"Expected 52 PDFs, found {len(pdfs)}")

    rows = [["study_id", "doi", "pdf_filename"]]
    for i, p in enumerate(pdfs, start=1):
        rows.append([f"S{i:03d}", doi_from_pdf_name(p.stem), p.name])

    OUT.parent.mkdir(parents=True, exist_ok=True)
    with OUT.open("w", newline="", encoding="utf-8") as f:
        csv.writer(f).writerows(rows)
    print(f"Wrote {OUT.relative_to(REPO)} with {len(pdfs)} studies.")


if __name__ == "__main__":
    main()
